import AppKit
import ApplicationServices
import Foundation

@MainActor
final class TextInsertionService {
    enum InsertResult {
        case pasted
        case copiedAccessibilityRequired
        case failed
    }

    private typealias ClipboardItemSnapshot = [(NSPasteboard.PasteboardType, Data)]
    private typealias ClipboardSnapshot = [ClipboardItemSnapshot]

    private static let pasteSessionType = NSPasteboard.PasteboardType("app.fugufableflow.PasteSession")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let legacyTransientType = NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")

    func requestAccessibilityPermission() -> Bool {
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        let trusted = AXIsProcessTrustedWithOptions(options)
        DiagnosticLog.insertion.info("requestAccessibilityPermission trusted=\(trusted, privacy: .public)")
        return trusted
    }

    func insert(_ text: String, restoreClipboard: Bool) async -> InsertResult {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            DiagnosticLog.insertion.info("insert skipped empty text")
            return .failed
        }

        let trusted = AXIsProcessTrusted()
        DiagnosticLog.insertion.info(
            "insert begin textLength=\(trimmed.count, privacy: .public) restoreClipboard=\(restoreClipboard, privacy: .public) accessibilityTrusted=\(trusted, privacy: .public)"
        )

        let pasteboard = NSPasteboard.general
        let savedContents = restoreClipboard ? Self.snapshotClipboard(from: pasteboard) : []
        let sessionID = UUID().uuidString

        let didSetString = Self.preparePasteboard(
            pasteboard,
            text: trimmed,
            sessionID: restoreClipboard ? sessionID : nil
        )
        DiagnosticLog.insertion.info("insert pasteboardSet=\(didSetString, privacy: .public) savedItems=\(savedContents.count, privacy: .public)")
        guard didSetString else { return .failed }

        guard trusted else {
            _ = requestAccessibilityPermission()
            DiagnosticLog.insertion.error("insert copiedOnly accessibilityTrusted=false")
            return .copiedAccessibilityRequired
        }

        try? await Task.sleep(nanoseconds: 250_000_000)
        let didPostPasteShortcut = await postPasteShortcut()
        DiagnosticLog.insertion.info("insert postedPasteShortcut")
        guard didPostPasteShortcut else { return .failed }

        guard restoreClipboard else { return .pasted }
        try? await Task.sleep(nanoseconds: 2_000_000_000)
        guard Self.pasteboardStillOwnedByPasteSession(
            pasteboard,
            expectedText: trimmed,
            sessionID: sessionID
        ) else {
            DiagnosticLog.insertion.info("insert skipRestore clipboardChanged")
            return .pasted
        }
        pasteboard.clearContents()
        if !savedContents.isEmpty {
            pasteboard.writeObjects(Self.pasteboardItems(from: savedContents))
        }
        DiagnosticLog.insertion.info("insert restoredClipboard")
        return .pasted
    }

    func captureSelectedText() async -> String {
        if let selectedText = accessibilitySelectedText(), !selectedText.isEmpty {
            DiagnosticLog.insertion.info("captureSelectedText axLength=\(selectedText.count, privacy: .public)")
            return selectedText
        }

        let pasteboard = NSPasteboard.general
        let savedContents = Self.snapshotClipboard(from: pasteboard)
        let initialChangeCount = pasteboard.changeCount

        guard AXIsProcessTrusted() else {
            _ = requestAccessibilityPermission()
            DiagnosticLog.insertion.error("captureSelectedText blocked accessibilityTrusted=false")
            return ""
        }

        let didPostCopy = await postKeyboardShortcut(keyCode: 0x08, flags: .maskCommand)
        guard didPostCopy else { return "" }
        try? await Task.sleep(nanoseconds: 180_000_000)

        let selectedText: String
        if pasteboard.changeCount != initialChangeCount {
            selectedText = pasteboard.string(forType: .string) ?? ""
        } else {
            selectedText = ""
        }

        pasteboard.clearContents()
        if !savedContents.isEmpty {
            pasteboard.writeObjects(Self.pasteboardItems(from: savedContents))
        }
        DiagnosticLog.insertion.info("captureSelectedText length=\(selectedText.count, privacy: .public)")
        return selectedText
    }

    private func accessibilitySelectedText() -> String? {
        guard AXIsProcessTrusted() else { return nil }

        let systemWideElement = AXUIElementCreateSystemWide()
        var focusedElementReference: CFTypeRef?
        let focusedStatus = AXUIElementCopyAttributeValue(
            systemWideElement,
            kAXFocusedUIElementAttribute as CFString,
            &focusedElementReference
        )
        guard focusedStatus == .success,
              let focusedElement = focusedElementReference else {
            return nil
        }

        var selectedTextReference: CFTypeRef?
        let selectedTextStatus = AXUIElementCopyAttributeValue(
            focusedElement as! AXUIElement,
            kAXSelectedTextAttribute as CFString,
            &selectedTextReference
        )
        guard selectedTextStatus == .success else {
            return nil
        }

        return selectedTextReference as? String
    }

    func pressEnter() async -> Bool {
        guard AXIsProcessTrusted() else {
            _ = requestAccessibilityPermission()
            DiagnosticLog.insertion.error("pressEnter blocked accessibilityTrusted=false")
            return false
        }
        return await postKeyboardShortcut(keyCode: 0x24, flags: [])
    }

    private static func preparePasteboard(
        _ pasteboard: NSPasteboard,
        text: String,
        sessionID: String?
    ) -> Bool {
        pasteboard.clearContents()
        pasteboard.declareTypes([
            .string,
            transientType,
            concealedType,
            autoGeneratedType,
            legacyTransientType,
            pasteSessionType
        ], owner: nil)
        pasteboard.setString(text, forType: .string)
        pasteboard.setString("", forType: transientType)
        pasteboard.setString("", forType: concealedType)
        pasteboard.setString("", forType: autoGeneratedType)
        pasteboard.setString("", forType: legacyTransientType)
        if let sessionID {
            pasteboard.setString(sessionID, forType: pasteSessionType)
        }
        return pasteboard.string(forType: .string) == text
    }

    private static func snapshotClipboard(from pasteboard: NSPasteboard) -> ClipboardSnapshot {
        (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in
                guard let data = item.data(forType: type) else { return nil }
                return (type, data)
            }
        }
    }

    private static func pasteboardStillOwnedByPasteSession(
        _ pasteboard: NSPasteboard,
        expectedText: String,
        sessionID: String
    ) -> Bool {
        pasteboard.string(forType: .string) == expectedText &&
            pasteboard.string(forType: pasteSessionType) == sessionID
    }

    private static func pasteboardItems(from snapshot: ClipboardSnapshot) -> [NSPasteboardItem] {
        snapshot.map { itemSnapshot in
            let item = NSPasteboardItem()
            for (type, data) in itemSnapshot {
                item.setData(data, forType: type)
            }
            return item
        }
    }

    private func postPasteShortcut() async -> Bool {
        guard AXIsProcessTrusted() else {
            DiagnosticLog.insertion.error("postPasteShortcut blocked accessibilityTrusted=false")
            return false
        }

        return await postKeyboardShortcut(keyCode: 0x09, flags: .maskCommand)
    }

    private func postKeyboardShortcut(keyCode: CGKeyCode, flags: CGEventFlags) async -> Bool {
        let source = CGEventSource(stateID: .privateState)
        let usesCommand = flags.contains(.maskCommand)
        let commandDown = usesCommand ? CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: true) : nil
        let commandUp = usesCommand ? CGEvent(keyboardEventSource: source, virtualKey: 0x37, keyDown: false) : nil
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            DiagnosticLog.insertion.error("postKeyboardShortcut failed createEvents")
            return false
        }

        commandDown?.flags = flags
        keyDown.flags = flags
        keyUp.flags = flags

        commandDown?.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: 10_000_000)
        keyDown.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: 10_000_000)
        keyUp.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: 10_000_000)
        commandUp?.post(tap: .cghidEventTap)
        return true
    }
}
